# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-pipelines
- main

pool: 
  vmImage: 'ubuntu-latest'  

variables:
  npm_config_cache: '$(Pipeline.Workspace)/.npm'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: 'npm | $(Agent.OS) | ./trainee_frontend/package-lock.json'
    path: $(npm_config_cache)
    cacheHitVar: NPM_CACHE_RESTORED
  condition: ne(variables['NPM_CACHE_RESTORED'], 'true')
  

- script: |
    echo -e "Executing Builds : $(System.DefaultWorkingDirectory)\n" && ls 
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: ./trainee_frontend/
  
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/trainee_frontend/build'
    output_location: '/trainee_frontend/build'
    skip_app_build: true
    skip_api_build: true
    app_build_command: 'npm run build'
    build_timeout_in_minutes: 10
    is_static_export: false
    verbose: true
    azure_static_web_apps_api_token: $(StaticWebAppApiToken)